model:
    name: CNN
    checkpoint: classifier/checkpoints/densenet169/best196.pkl
dataset:
    name: MimicDataset
    task: six
    return_image: True
experiment:
    name: densenet169_mimic_six
    output_dir: linguistics/embeddings/output/
    save_vectors: False
    plot_split:
        - val
        - test