model:
    name: Doc2vec
    checkpoint: linguistics/embeddings/output/doc2vec_mimic/DBOW_vector768_window8_count15_epoch100_mimic.doc2vec
dataset:
    name: MimicDataset
    task: six
report:
    report_policy: top_section_MIT-LCP
experiment:
    name: doc2vec_mimic_50_mit
    output_dir: linguistics/embeddings/output/
    save_vectors: True
    plot_split:
        - val
        - test
        - train