model:
    name: Doc2vec
    checkpoint: linguistics/embeddings/checkpoints/DBOW_vector300_window8_count15_epoch100_mimic/DBOW_vector300_window8_count15_epoch100_mimic.doc2vec
dataset:
    name: MimicDataset
    task: six
report:
    report_policy: top_section
experiment:
    name: doc2vec_mimic_six
    save_vectors: False
    output_dir: linguistics/embeddings/output/
