model:
    name: Doc2vec
    to_train: True
    vector_size: 768
    epochs: 50
dataset:
    name: MimicDataset
    task: six
report:
    report_policy: top_section_MIT-LCP
experiment:
    name: doc2vec_mimic_mit
    output_dir: linguistics/embeddings/output/
    save_vectors: True
    plot_split:
        - val
        - test
        - train