model:
    name: Doc2vec
    to_train: True
    vector_size: 768
    epochs: 100
dataset:
    name: MimicDataset
report:
    report_policy: top_section
experiment:
    name: doc2vec_mimic
    save_vectors: False
    output_dir: linguistics/embeddings/output/
